version: "3.8"

services:
  mysqldb:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 201JFT1884
      MYSQL_DATABASE: stationSki
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: ibtihel12345/stationski-app:v1.0
    restart: on-failure
    ports:
      - "8090:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "201JFT1884",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
