version: "3.8"

services:
  mysqldb:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=223JFT5239
      - MYSQL_DATABASE=stationSki  # Alignement avec la configuration Spring Boot
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3309:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: ibtihel12345/stationski-app:v1.0  # Utilisation de l'image existante si nécessaire
    restart: on-failure
    ports:
      - "8089:8089"  # Alignement avec la configuration Spring Boot
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
