
services:
  mysqldb:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Permettre la connexion sans mot de passe
      MYSQL_DATABASE: stationSki  # Nom de la base de données à créer
    ports:
    - "3310:3306" # Port local 3308 redirigé vers 3306 à l'intérieur du conteneur
    volumes:
      - db:/var/lib/mysql  # Persistance des données

  app:
    depends_on:
      - mysqldb  # L'application dépend du service MySQL
    image: ibtihel12345/stationski-app:v1.0
    restart: on-failure
    ports:
      - "8090:8089"  # Port local 8090 redirigé vers 8089 à l'intérieur du conteneur
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",  # Pas de mot de passe
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    volumes:
      - .m2:/root/.m2  # Montée du répertoire Maven local pour les dépendances
    stdin_open: true  # Ouvre un stdin pour le conteneur
    tty: true  # Alloue un terminal pour le conteneur

volumes:
  db:  # Volume pour persister les données MySQL
